services:
    auth:
      build:
        context: ../../apps/auth
        dockerfile: dev.Dockerfile
      # ports:
      #   - 3000:3000
      volumes:
        - ../../apps/auth:/app
      environment:
        NODE_ENV: development
        EXPIRES: 3600

      secrets:
        - MONGO_URI
        - JWT_KEY
        - OSS_ACCESS_KEY_SECRET
        - OSS_ACCESS_KEY_ID

    books:
      build:
        context: ../../apps/books
        dockerfile: dev.Dockerfile
      # ports:
      #   - 3000:3000
      volumes:
        - ../../apps/books/src:/app/src
      environment:
        NODE_ENV: development
        EXPIRES: 3600
      secrets:
        - MONGO_URI
        - JWT_KEY
        - OSS_ACCESS_KEY_SECRET
        - OSS_ACCESS_KEY_ID

    nginx:
      image: nginx:1.25-alpine-slim
      ports:
        - 80:80
      volumes:
        - ../nginx/nginx.conf:/etc/nginx/nginx.conf

secrets:
  MONGO_URI:
    file: ./secrets/.MONGO_URI.txt
  JWT_KEY:
    file: ./secrets/.JWT_KEY.txt
  OSS_ACCESS_KEY_SECRET:
    file: ./secrets/.OSS_ACCESS_KEY_SECRET.txt
  OSS_ACCESS_KEY_ID:
    file: ./secrets/.OSS_ACCESS_KEY_ID.txt
  
