services:
    auth:
      build:
        context: ../../apps/auth
        dockerfile: dev.Dockerfile
      ports:
        - 3000:3000
      volumes:
        - ../../apps/auth:/app
      secrets:
        - MONGO_URI
        - JWT_KEY
        - Access_Key_Secret

    nginx:
      image: nginx:1.25-alpine-slim
      ports:
        - 80:80
      volumes:
        - ../nginx/nginx.conf:/etc/nginx/nginx.conf

secrets:
  MONGO_URI:
    file: ./secrets/.MONGO_URI.txt
  JWT_KEY:
    file: ./secrets/.JWT_KEY.txt
  Access_Key_Secret:
    file: ./secrets/.Access_Key_Secret.txt
  
