apiVersion: skaffold/v2alpha3
kind: Config
# deploy:
  # kubectl:
    # manifests:
    #   - ./infra/k8s/auth/*
    #   # - ./infra/k8s/books/*
    #   - ./infra/k8s/ingress-srv.yaml
    #   - ./infra/k8s/oss-secret.yaml
build:
  local:
    push: false
  artifacts:
    - image: zhangshihao/auth
      context: ./apps/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: zhangshihao/books
      context: ./apps/books
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
