apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      name: books-pod
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: zhangshihao/books
          env:
            - name: MONGO_URI
              value: "mongodb://books-mongo-srv:27017/books"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: books-srv
spec:
  selector:
    app: books
  ports:
    - name: books
      protocol: TCP
      port: 3000
      targetPort: 3000
